export const FlagCard = [
  { id: 1, value: "Visa" },
  { id: 2, value: "Mastercard" },
  { id: 3, value: "American Express" },
  { id: 4, value: "Sorocred" },
  { id: 5, value: "Diners Club" },
  { id: 6, value: "Elo" },
  { id: 7, value: "Hipercard" },
  { id: 8, value: "Aura" },
  { id: 9, value: "Cabal" },
  { id: 10, value: "Alelo" },
  { id: 11, value: "Banes Card" },
  { id: 12, value: "CalCard" },
  { id: 13, value: "Credz" },
  { id: 14, value: "Discover" },
  { id: 15, value: "GoodCard" },
  { id: 16, value: "GreenCard" },
  { id: 17, value: "Hiper" },
  { id: 18, value: "JcB" },
  { id: 19, value: "Mais" },
  { id: 20, value: "MaxVan" },
  { id: 21, value: "Policard" },
  { id: 22, value: "RedeCompras" },
  { id: 23, value: "Sodexo" },
  { id: 24, value: "ValeCard" },
  { id: 25, value: "Verocheque" },
  { id: 26, value: "VR" },
  { id: 27, value: "Ticket" },
  { id: 99, value: "Outros" },
];
