export enum StorageNames {
  Handler = "Handler",
  Integrated_Handler = "Integrated_Handler",
  ItemOutCart = "ItemOutCart",
  Not_Integrated_ItemOutCart = "Not_Integrated_ItemOutCart",
  Integrated_ItemOutCart = "Integrated_ItemOutCart",
  Product = "Product",
  Purchase_Product = "Purchase_Product",
  Sale = "Sale",
  Not_Integrated_Sale = "Not_Integrated_Sale",
  Integrated_Sale = "Integrated_Sale",
  Step_Sale = "Step_Sale",
  Delivery_Sale = "Delivery_Sale",
  Settings = "Settings",
  Store = "Store",
  StoreCash = "StoreCash",
  User = "User",
  Errors = "Errors",
  Apm_Temp = "Apm_Temp",
  Old_Cash_History = "Old_Cash_History",
  Product_Wast = "Product_Wast",
  Products_To_Waste = "Products_To_Waste",
  Payment_Tef_Audit = "Payment_Tef_Audit",
  Not_Integrated_Payment_Tef_Audit = "Not_Integrated_Payment_Tef_Audit"
}
