export enum StorageNames {
  Handler = "Handler",
  Integrated_Handler = "Integrated_Handler",
  ItemOutCart = "ItemOutCart",
  Not_Integrated_ItemOutCart = "Not_Integrated_ItemOutCart",
  Integrated_ItemOutCart = "Integrated_ItemOutCart",
  Product = "Product",
  Purchase_Product = "Purchase_Product",
  Sale = "Sale",
  Not_Integrated_Sale = "Not_Integrated_Sale",
  Integrated_Sale = "Integrated_Sale",
  Step_Sale = "Step_Sale",
  Delivery_Sale = "Delivery_Sale",
  Settings = "Settings",
  Store = "Store",
  StoreCash = "StoreCash",
  User = "User",
  Errors = "Errors",
  Apm_Temp = "Apm_Temp",
  Old_Cash_History = "Old_Cash_History",
  PRODUCT_WAST = "PRODUCT_WAST",
}
